#define DEFAULTS [NSUserDefaults standardUserDefaults]

#define APPIUM_PLIST_ANDROID_ACTIVITY @"Android Activity"
#define APPIUM_PLIST_ANDROID_APP_PATH @"Android App Path"
#define APPIUM_PLIST_ANDROID_AUTOMATION_NAME @"Android Automation Name"
#define APPIUM_PLIST_ANDROID_AVD @"Android AVD"
#define APPIUM_PLIST_ANDROID_AVD_ARGUMENTS @"Android AVD Arguments"
#define APPIUM_PLIST_ANDROID_BOOTSTRAP_PORT @"Android Boostrap Port"
#define APPIUM_PLIST_ANDROID_BROWSER_NAME @"Android Browser Name"
#define APPIUM_PLIST_ANDROID_CHROMEDRIVER_EXECUTABLE_PATH @"Android Chromedriver Executable Path"
#define APPIUM_PLIST_ANDROID_CHROMEDRIVER_PORT @"Android Chromedriver Port"
#define APPIUM_PLIST_ANDROID_COVERAGE_CLASS @"Android Coverage Class"
#define APPIUM_PLIST_ANDROID_CUSTOM_SDK_PATH @"Android Custom SDK Path"
#define APPIUM_PLIST_ANDROID_DEVICE_NAME @"Android Device Name"
#define APPIUM_PLIST_ANDROID_DEVICE_READY_TIMEOUT @"Android Device Ready Timeout"
#define APPIUM_PLIST_ANDROID_DONT_STOP_APP_ON_RESET @"Android Don't Stop App On Reset"
#define APPIUM_PLIST_ANDROID_FULL_RESET @"Android Full Reset"
#define APPIUM_PLIST_ANDROID_INTENT_ACTION @"Android Intent Action"
#define APPIUM_PLIST_ANDROID_INTENT_CATEGORY @"Android Intent Category"
#define APPIUM_PLIST_ANDROID_INTENT_FLAGS @"Android Intent Flags"
#define APPIUM_PLIST_ANDROID_INTENT_ARGUMENTS @"Android Intent Arguments"
#define APPIUM_PLIST_ANDROID_KEY_ALIAS @"Android Key Alias"
#define APPIUM_PLIST_ANDROID_KEY_PASSWORD @"Android Key Password"
#define APPIUM_PLIST_ANDROID_KEYSTORE_PASSWORD @"Android Keystore Password"
#define APPIUM_PLIST_ANDROID_KEYSTORE_PATH @"Android Keystore Path"
#define APPIUM_PLIST_ANDROID_LANGUAGE @"Android Language"
#define APPIUM_PLIST_ANDROID_LOCALE @"Android Locale"
#define APPIUM_PLIST_ANDROID_NO_RESET @"Android No Reset"
#define APPIUM_PLIST_ANDROID_PACKAGE @"Android Package"
#define APPIUM_PLIST_ANDROID_PLATFORM_NAME @"Android Platform Name"
#define APPIUM_PLIST_ANDROID_PLATFORM_VERSION @"Android Platform Version"
#define APPIUM_PLIST_ANDROID_SELENDROID_PORT @"Android Selendroid Port"
#define APPIUM_PLIST_ANDROID_USE_ACTIVITY @"Android Use Activity"
#define APPIUM_PLIST_ANDROID_USE_APP_PATH @"Android Use App Path"
#define APPIUM_PLIST_ANDROID_USE_AVD @"Android Use AVD"
#define APPIUM_PLIST_ANDROID_USE_AVD_ARGUMENTS @"Android Use AVD Arguments"
#define APPIUM_PLIST_ANDROID_USE_BOOTSTRAP_PORT @"Android Use Boostrap Port"
#define APPIUM_PLIST_ANDROID_USE_BROWSER @"Android Use Android Browser"
#define APPIUM_PLIST_ANDROID_USE_CHROMEDRIVER_EXECUTABLE_PATH @"Android Use Chromedriver Executable Path"
#define APPIUM_PLIST_ANDROID_USE_CHROMEDRIVER_PORT @"Android Use Chromedriver Port"
#define APPIUM_PLIST_ANDROID_USE_COVERAGE_CLASS @"Android Use Coverage Class"
#define APPIUM_PLIST_ANDROID_USE_CUSTOM_SDK_PATH @"Android Use Custom SDK Path"
#define APPIUM_PLIST_ANDROID_USE_DEVICE_NAME @"Android Use Device Name"
#define APPIUM_PLIST_ANDROID_USE_DEVICE_READY_TIMEOUT @"Android Use Device Ready Timeout"
#define APPIUM_PLIST_ANDROID_USE_INTENT_ACTION @"Android Use Intent Action"
#define APPIUM_PLIST_ANDROID_USE_INTENT_CATEGORY @"Android Use Intent Category"
#define APPIUM_PLIST_ANDROID_USE_INTENT_FLAGS @"Android Use Intent Flags"
#define APPIUM_PLIST_ANDROID_USE_INTENT_ARGUMENTS @"Android Use Intent Arguments"
#define APPIUM_PLIST_ANDROID_USE_KEYSTORE @"Android Use Keystore"
#define APPIUM_PLIST_ANDROID_USE_LANGUAGE @"Android Use Language"
#define APPIUM_PLIST_ANDROID_USE_LOCALE @"Android Use Locale"
#define APPIUM_PLIST_ANDROID_USE_PACKAGE @"Android Use Package"
#define APPIUM_PLIST_ANDROID_USE_SELENDROID_PORT @"Android Use Selendroid Port"
#define APPIUM_PLIST_ANDROID_USE_WAIT_ACTIVITY @"Android Use Wait Activity"
#define APPIUM_PLIST_ANDROID_USE_WAIT_PACKAGE @"Android Use Wait Package"
#define APPIUM_PLIST_ANDROID_WAIT_ACTIVITY @"Android Wait Activity"
#define APPIUM_PLIST_ANDROID_WAIT_PACKAGE @"Android Wait Package"
#define APPIUM_PLIST_BREAK_ON_NODEJS_APP_START @"Break On NodeJS Application Start"
#define APPIUM_PLIST_BYPASS_PERMISSIONS_CHECKS @"Bypass Permissions Checks"
#define APPIUM_PLIST_CALLBACK_ADDRESS @"Callback Address"
#define APPIUM_PLIST_CALLBACK_PORT @"Callback Port"
#define APPIUM_PLIST_CHECK_FOR_UPDATES @"Check For Updates"
#define APPIUM_PLIST_COMMAND_TIMEOUT @"Command Timeout"
#define APPIUM_PLIST_CUSTOM_FLAGS @"Custom Flags"
#define APPIUM_PLIST_DEVELOPER_MODE @"Developer Mode"
#define APPIUM_PLIST_ENVIRONMENT_VARIABLES @"Environment Variables"
#define APPIUM_PLIST_EXTERNAL_APPIUM_PACKAGE_PATH @"External Appium Package Path"
#define APPIUM_PLIST_EXTERNAL_NODEJS_BINARY_PATH @"External NodeJS Binary Path"
#define APPIUM_PLIST_INSPECTOR_CODEMAKER_LANGUAGE @"Inspector CodeMaker Language"
#define APPIUM_PLIST_INSPECTOR_SEARCH_FOR_LOCATORS_FROM_CURRENT_ELEMENT @"Inspector Search For Locators From Current Element"
#define APPIUM_PLIST_INSPECTOR_SHOWS_DISABLED_ELEMENTS @"Inspector Shows Disabled Elements"
#define APPIUM_PLIST_INSPECTOR_SHOWS_INVISIBLE_ELEMENTS @"Inspector Shows Invisible Elements"
#define APPIUM_PLIST_INSPECTOR_USES_CODEMAKER_BOILERPLATE @"Inspector Uses CodeMaker Boilerplate"
#define APPIUM_PLIST_INSPECTOR_USES_XPATH_ONLY @"Inspector Uses XPath Only"
#define APPIUM_PLIST_IOS_APP_PATH @"iOS App Path"
#define APPIUM_PLIST_IOS_AUTHORIZED @"iOS Authorized"
#define APPIUM_PLIST_IOS_BACKEND_RETRIES @"iOS Backend Retries"
#define APPIUM_PLIST_IOS_BUNDLEID @"iOS BundleID"
#define APPIUM_PLIST_IOS_CALENDAR_FORMAT @"iOS Calendar Format"
#define APPIUM_PLIST_IOS_CUSTOM_TRACE_TEMPLATE_PATH @"iOS Custom Trace Template Path"
#define APPIUM_PLIST_IOS_DEVICE_NAME @"iOS Device Name"
#define APPIUM_PLIST_IOS_FULL_RESET @"iOS Full Reset"
#define APPIUM_PLIST_IOS_INSTRUMENTS_BINARY_PATH @"iOS Instruments Binary Path"
#define APPIUM_PLIST_IOS_ISOLATE_SIM_DEVICE @"iOS Isolate Sim Device"
#define APPIUM_PLIST_IOS_KEEP_KEYCHAINS @"iOS Keep Keychains"
#define APPIUM_PLIST_IOS_LANGUAGE @"iOS Language"
#define APPIUM_PLIST_IOS_LAUNCH_TIMEOUT @"iOS Launch Timeout"
#define APPIUM_PLIST_IOS_LOCALE @"iOS Locale"
#define APPIUM_PLIST_IOS_LOCALIZABLE_STRING_DIRECTORY @"iOS Localizable Strings Directory"
#define APPIUM_PLIST_IOS_NO_RESET @"iOS No Reset"
#define APPIUM_PLIST_IOS_ORIENTATION @"iOS Orientation"
#define APPIUM_PLIST_IOS_PLATFORM_VERSION @"iOS Platform Version"
#define APPIUM_PLIST_IOS_SHOW_SIMULATOR_LOG @"iOS Show Simulator Log"
#define APPIUM_PLIST_IOS_SHOW_SYSTEM_LOG @"iOS Show System Log"
#define APPIUM_PLIST_IOS_TRACE_DIRECTORY @"iOS Trace Directory"
#define APPIUM_PLIST_IOS_UDID @"iOS UDID"
#define APPIUM_PLIST_IOS_USE_APP_PATH @"iOS Use App Path"
#define APPIUM_PLIST_IOS_USE_BACKEND_RETRIES @"iOS Use Backend Retries"
#define APPIUM_PLIST_IOS_USE_BUNDLEID @"iOS Use BundleID"
#define APPIUM_PLIST_IOS_USE_CALENDAR @"iOS Use Calendar"
#define APPIUM_PLIST_IOS_USE_CUSTOM_TRACE_TEMPLATE @"iOS Use Custom Trace Template"
#define APPIUM_PLIST_IOS_USE_DEFAULT_DEVICE @"iOS Use Default Device"
#define APPIUM_PLIST_IOS_USE_INSTRUMENTS_BINARY_PATH @"iOS Use Instruments Binary Path"
#define APPIUM_PLIST_IOS_USE_LANGUAGE @"iOS Use Language"
#define APPIUM_PLIST_IOS_USE_LAUNCH_TIMEOUT @"iOS Use Launch Timeout"
#define APPIUM_PLIST_IOS_USE_LOCALE @"iOS Use Locale"
#define APPIUM_PLIST_IOS_USE_LOCALIZABLE_STRINGS_DIRECTORY @"iOS Use Localizable Strings Directory"
#define APPIUM_PLIST_IOS_USE_MOBILE_SAFARI @"iOS Use Mobile Safari"
#define APPIUM_PLIST_IOS_USE_NATIVE_INSTRUMENTS_LIBRARY @"iOS Use Native Instruments Library"
#define APPIUM_PLIST_IOS_USE_ORIENTATION @"iOS Use Orientation"
#define APPIUM_PLIST_IOS_USE_TRACE_DIRECTORY @"iOS Use Trace Directory"
#define APPIUM_PLIST_IOS_USE_UDID @"iOS Use UDID"
#define APPIUM_PLIST_KILL_PROCESSES_USING_PORT @"Kill Processes Using Port"
#define APPIUM_PLIST_LOG_COLORS @"Log Colors"
#define APPIUM_PLIST_LOG_FILE @"Log File"
#define APPIUM_PLIST_LOG_LEVEL @"Log Level"
#define APPIUM_PLIST_LOG_TIMESTAMPS @"Log Timestamps"
#define APPIUM_PLIST_LOG_WEBHOOK @"Log Webhook"
#define APPIUM_PLIST_LOG_FORCE_SCROLL @"Force Scroll Log"
#define APPIUM_PLIST_MAXIMUM_LOG_LENGTH @"Maximum Log Length"
#define APPIUM_PLIST_NEW_COMMAND_TIMEOUT @"New Command Timeout"
#define APPIUM_PLIST_NODEJS_DEBUG_PORT @"NodeJS Debug Port"
#define APPIUM_PLIST_OVERRIDE_EXISTING_SESSIONS @"Override Existing Sessions"
#define APPIUM_PLIST_PLATFORM_IS_ANDROID @"Platform is Android"
#define APPIUM_PLIST_PRELAUNCH_APPLICATION @"Prelaunch Application"
#define APPIUM_PLIST_ROBOT_ADDRESS @"Robot Address"
#define APPIUM_PLIST_ROBOT_PORT @"Robot Port"
#define APPIUM_PLIST_SELENIUM_GRID_CONFIG_FILE @"Selenium Grid Configuration File"
#define APPIUM_PLIST_SERVER_ADDRESS @"Server Address"
#define APPIUM_PLIST_SERVER_PORT @"Server Port"
#define APPIUM_PLIST_TEMP_FOLDER_PATH @"Temp Folder Path"
#define APPIUM_PLIST_USE_ADDITIONAL_LOG_SPACING @"Use Additional Log Spacing"
#define APPIUM_PLIST_USE_CALLBACK_ADDRESS @"Use Callback Address"
#define APPIUM_PLIST_USE_CALLBACK_PORT @"Use Callback Port"
#define APPIUM_PLIST_USE_CUSTOM_FLAGS @"Use Custom Flags"
#define APPIUM_PLIST_USE_EXTERNAL_APPIUM_PACKAGE @"Use External Appium Package"
#define APPIUM_PLIST_USE_EXTERNAL_NODEJS_BINARY @"Use External NodeJS Binary"
#define APPIUM_PLIST_USE_LOCAL_TIMEZONE @"Use Local Timezone"
#define APPIUM_PLIST_USE_LOG_FILE @"Use Log File"
#define APPIUM_PLIST_USE_LOG_TIMESTAMPS @"Use Log Timestamps"
#define APPIUM_PLIST_USE_LOG_WEBHOOK @"Use Log Webhook"
#define APPIUM_PLIST_USE_NEW_COMMAND_TIMEOUT @"Use New Command Timeout"
#define APPIUM_PLIST_USE_NODEJS_DEBUGGING @"Use NodeJS Debugging"
#define APPIUM_PLIST_USE_REMOTE_SERVER @"Use Remote Server"
#define APPIUM_PLIST_USE_ROBOT @"Use Robot"
#define APPIUM_PLIST_USE_SELENIUM_GRID_CONFIG_FILE @"Use Selenium Grid Config File"
#define APPIUM_PLIST_USE_STRICT_CAPABILITIES @"Use Strict Capabilities"
#define APPIUM_PLIST_USE_TEMP_FOLDER_PATH @"Use Temp Folder Path"
