//
//  AppiumPreferencesFile.h
//  Appium
//
//  Created by Dan Cuellar on 4/12/13.
//  Copyright (c) 2013 Appium. All rights reserved.
//

#define APPIUM_PLIST_ANDROID_ACTIVITY @"Android Activity"
#define APPIUM_PLIST_ANDROID_DEVICE_READY_TIMEOUT @"Android Device Ready Timeout"
#define APPIUM_PLIST_ANDROID_FULL_RESET @"Android Full Reset"
#define APPIUM_PLIST_ANDROID_KEY_ALIAS @"Android Key Alias"
#define APPIUM_PLIST_ANDROID_KEY_PASSWORD @"Android Key Password"
#define APPIUM_PLIST_ANDROID_KEYSTORE_PASSWORD @"Android Keystore Password"
#define APPIUM_PLIST_ANDROID_KEYSTORE_PATH @"Android Keystore Path"
#define APPIUM_PLIST_ANDROID_PACKAGE @"Android Package"
#define APPIUM_PLIST_ANDROID_WAIT_ACTIVITY @"Android Wait Activity"
#define APPIUM_PLIST_APP_PATH @"App Path"
#define APPIUM_PLIST_AUTHORIZED_IOS @"Authorized iOS"
#define APPIUM_PLIST_AVD @"AVD"
#define APPIUM_PLIST_BREAK_ON_NODEJS_APP_START @"Break On NodeJS Application Start"
#define APPIUM_PLIST_BUNDLEID @"BundleID"
#define APPIUM_PLIST_CALENDAR_FORMAT @"Calendar Format"
#define APPIUM_PLIST_CODEMAKER_LANGUAGE @"CodeMaker Language"
#define APPIUM_PLIST_CHECK_FOR_UPDATES @"Check For Updates"
#define APPIUM_PLIST_CUSTOM_ANDROID_SDK_PATH @"Custom Android SDK Path"
#define APPIUM_PLIST_DEVICE @"Device"
#define APPIUM_PLIST_DEVELOPER_MODE @"Developer Mode"
#define APPIUM_PLIST_ENABLE_APPIUM_INSPECTOR_WINDOW_SUPPORT @"Enable Appium Inspector Window Support"
#define APPIUM_PLIST_EXTERNAL_APPIUM_PACKAGE_PATH @"External Appium Package Path"
#define APPIUM_PLIST_EXTERNAL_NODEJS_BINARY_PATH @"External NodeJS Binary Path"
#define APPIUM_PLIST_FORCE_CALENDAR @"Force Calendar"
#define APPIUM_PLIST_FORCE_DEVICE @"Force Device"
#define APPIUM_PLIST_FORCE_DEVICE_IPAD @"iPad"
#define APPIUM_PLIST_FORCE_DEVICE_IPHONE @"iPhone"
#define APPIUM_PLIST_FORCE_LANGUAGE @"Force Language"
#define APPIUM_PLIST_FORCE_LOCALE @"Force Locale"
#define APPIUM_PLIST_FORCE_ORIENTATION @"Force Orientation"
#define APPIUM_PLIST_FORCE_ORIENTATION_PORTRAIT @"Portrait"
#define APPIUM_PLIST_FORCE_ORIENTATION_LANDSCAPE @"Landscape"
#define APPIUM_PLIST_INSPECTOR_SHOWS_DISABLED_ELEMENTS @"Inspector Shows Disabled Elements"
#define APPIUM_PLIST_INSPECTOR_SHOWS_INVISIBLE_ELEMENTS @"Inspector Shows Invisible Elements"
#define APPIUM_PLIST_KEEP_ARTIFACTS @"Keep Artifacts"
#define APPIUM_PLIST_KILL_PROCESSES_USING_PORT @"Kill Processes Using Port"
#define APPIUM_PLIST_LANGUAGE @"Language"
#define APPIUM_PLIST_LOCALE @"Locale"
#define APPIUM_PLIST_LOG_FILE @"Log File"
#define APPIUM_PLIST_LOG_WEBHOOK @"Log Webhook"
#define APPIUM_PLIST_NODEJS_DEBUG_PORT @"NodeJS Debug Port"
#define APPIUM_PLIST_ORIENTATION @"Orientation"
#define APPIUM_PLIST_OVERRIDE_EXISTING_SESSIONS @"Override Existing Sessions"
#define APPIUM_PLIST_TAB_STATE @"Tab State"
#define APPIUM_PLIST_TAB_STATE_ANDROID 1
#define APPIUM_PLIST_TAB_STATE_IOS 0
#define APPIUM_PLIST_PRELAUNCH @"Prelaunch"
#define APPIUM_PLIST_RESET_APPLICATION_STATE @"Reset Application State"
#define APPIUM_PLIST_ROBOT_ADDRESS @"Robot Address"
#define APPIUM_PLIST_ROBOT_PORT @"Robot Port"
#define APPIUM_PLIST_SELENDROID_PORT @"Selendroid Port"
#define APPIUM_PLIST_SELENIUM_GRID_CONFIG_FILE @"Selenium Grid Config File"
#define APPIUM_PLIST_SERVER_ADDRESS @"Server Address"
#define APPIUM_PLIST_SERVER_PORT @"Server Port"
#define APPIUM_PLIST_UDID @"UDID"
#define APPIUM_PLIST_USE_ANDROID_ACTIVITY @"Use Android Activity"
#define APPIUM_PLIST_USE_ANDROID_BROWSER @"Use Android Browser"
#define APPIUM_PLIST_USE_ANDROID_DEVICE_READY_TIMEOUT @"Use Android Device Ready Timeout"
#define APPIUM_PLIST_USE_ANDROID_KEYSTORE @"Use Android Keystore"
#define APPIUM_PLIST_USE_ANDROID_PACKAGE @"Use Android Package"
#define APPIUM_PLIST_USE_ANDROID_WAIT_ACTIVITY @"Use Android Wait Activity"
#define APPIUM_PLIST_USE_APP_PATH @"Use App Path"
#define APPIUM_PLIST_USE_AVD @"Use AVD"
#define APPIUM_PLIST_USE_BUNDLEID @"Use BundleID"
#define APPIUM_PLIST_USE_CODEMAKER_BOILERPLATE @"Use CodeMaker Boilerplate"
#define APPIUM_PLIST_USE_CUSTOM_ANDROID_SDK_PATH @"Use Custom Android SDK Path"
#define APPIUM_PLIST_USE_EXTERNAL_APPIUM_PACKAGE @"Use External Appium Package"
#define APPIUM_PLIST_USE_EXTERNAL_NODEJS_BINARY @"Use External NodeJS Binary"
#define APPIUM_PLIST_USE_LOG_FILE @"Use Log File"
#define APPIUM_PLIST_USE_LOG_WEBHOOK @"Use Log Webhook"
#define APPIUM_PLIST_USE_NODEJS_DEBUGGING @"Use NodeJS Debugging"
#define APPIUM_PLIST_USE_REMOTE_SERVER @"Use Remote Server"
#define APPIUM_PLIST_USE_MOBILE_SAFARI @"Use Mobile Safari"
#define APPIUM_PLIST_USE_QUIET_LOGGING @"Use Quiet Logging"
#define APPIUM_PLIST_USE_ROBOT @"Use Robot"
#define APPIUM_PLIST_USE_SELENDROID_PORT @"Use Selendroid Port"
#define APPIUM_PLIST_USE_SELENIUM_GRID_CONFIG_FILE @"Use Selenium Grid Config File"
#define APPIUM_PLIST_USE_UDID @"Use UDID"
#define APPIUM_PLIST_USE_XPATH_ONLY @"Use XPath Only"
#define APPIUM_PLIST_USE_NATIVE_INSTRUMENTS_LIB @"Use Native Instruments Lib"
